// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Agreement: typeof import('./src/components/Agreement/index.vue')['default']
    AgreementPopup: typeof import('./src/components/AgreementPopup/index.vue')['default']
    BelongCity: typeof import('./src/components/BelongCity/index.vue')['default']
    CityPicker: typeof import('./src/components/CityPicker/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NumberRule: typeof import('./src/components/NumberRule/index.vue')['default']
    PhoneList: typeof import('./src/components/PhoneList/index.vue')['default']
    SearchNumber: typeof import('./src/components/SearchNumber/index.vue')['default']
    SelectNumber: typeof import('./src/components/SelectNumber/index.vue')['default']
    Tab1: typeof import('./src/components/Tab1/index.vue')['default']
    Tab2: typeof import('./src/components/Tab2/index.vue')['default']
    Tab3: typeof import('./src/components/Tab3/index.vue')['default']
    Tabs: typeof import('./src/components/Tabs/index.vue')['default']
    TogglePage: typeof import('./src/components/TogglePage/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
