// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Tab1: typeof import('./src/components/Tab1/index.vue')['default']
    Tab2: typeof import('./src/components/Tab2/index.vue')['default']
    Tab3: typeof import('./src/components/Tab3/index.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
